// Generated by editor/pipeline/graphics.py from the files in this folder. Do not edit.
import React from 'react';
import {Scene as S0} from './FactoryEvolution';
import {Scene as S1} from './StepFlow';
export const CUSTOM: [string, React.FC<any>][] = [
  ['FactoryEvolution', S0],
  ['StepFlow', S1],
];
