// Generated by editor/pipeline/graphics.py from the files in this folder. Do not edit.
import React from 'react';
import {Scene as S0} from './StepFlow';
export const CUSTOM: [string, React.FC<any>][] = [
  ['StepFlow', S0],
];
