"""Render graphic / image beats as short clips with Remotion."""
import hashlib
import json
import os
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path

from .media import MediaError
from .plan import Beat
from .styles import Style

REMOTION_DIR = Path(__file__).resolve().parent.parent / "remotion"
BROWSER = os.environ.get(
    "EDITOR_BROWSER", "/opt/pw-browsers/chromium_headless_shell-1194/chrome-linux/headless_shell")


def _style_props(style: Style) -> dict:
    return {"palette": style.palette, "fonts": style.fonts, "texture": style.texture}


def _source_hash() -> str:
    h = hashlib.sha1()
    for d in ("src", "public"):
        for f in sorted((REMOTION_DIR / d).rglob("*")):
            if f.is_file():
                h.update(str(f.relative_to(REMOTION_DIR)).encode() + f.read_bytes())
    return h.hexdigest()


CUSTOM_DIR = REMOTION_DIR / "src" / "custom"


def custom_scenes() -> list[str]:
    return sorted(p.stem for p in CUSTOM_DIR.glob("*.tsx") if p.stem[0].isupper())


def write_registry() -> None:
    """src/custom/registry.ts lists every custom scene so Root.tsx registers it as custom-<Name>."""
    names = custom_scenes()
    lines = ["// Generated by editor/pipeline/graphics.py from the files in this folder. Do not edit.",
             "import React from 'react';"]
    lines += [f"import {{Scene as S{i}}} from './{n}';" for i, n in enumerate(names)]
    lines.append("export const CUSTOM: [string, React.FC<any>][] = [")
    lines += [f"  ['{n}', S{i}]," for i, n in enumerate(names)]
    lines.append("];\n")
    text = "\n".join(lines)
    reg = CUSTOM_DIR / "registry.ts"
    if not reg.exists() or reg.read_text(encoding="utf-8") != text:
        reg.write_text(text, encoding="utf-8")


def ensure_bundle(out_dir: Path | None = None) -> Path:
    """Bundle the Remotion project once; later renders reuse it (rebuilt only if src/ changes)."""
    write_registry()
    out_dir = Path(out_dir or REMOTION_DIR / "out" / "bundle").resolve()
    stamp, key = out_dir / ".source-hash", _source_hash()
    if (out_dir / "index.html").exists() and stamp.exists() and stamp.read_text() == key:
        return out_dir
    shutil.rmtree(out_dir, ignore_errors=True)
    proc = subprocess.run(["npx", "remotion", "bundle", "src/index.ts", f"--out-dir={out_dir}",
                           "--public-dir=public", "--log=error"], cwd=REMOTION_DIR, capture_output=True, text=True)
    if proc.returncode != 0:
        raise MediaError(f"فشل تجهيز الگرافيكس (remotion bundle): {(proc.stderr or proc.stdout).strip()[-800:]}")
    stamp.write_text(key)
    return out_dir


@dataclass
class RenderJob:
    comp: str
    props: dict
    out: Path
    scale: float = 1.0
    still: bool = False


def render_batch(jobs: list[RenderJob], bundle: Path) -> None:
    """Render all jobs with one Node process and one browser (render-batch.mjs)."""
    if not jobs:
        return
    spec = {"serveUrl": str(Path(bundle).resolve()), "browserExecutable": BROWSER, "concurrency": 4,
            "items": [{"comp": j.comp, "props": j.props, "out": str(Path(j.out).resolve()), "scale": j.scale,
                       "still": j.still} for j in jobs]}
    spec_file = Path(jobs[0].out).resolve().parent / "render_jobs.json"
    spec_file.write_text(json.dumps(spec, ensure_ascii=False), encoding="utf-8")
    proc = subprocess.run(["node", "render-batch.mjs", str(spec_file)], cwd=REMOTION_DIR, capture_output=True, text=True)
    errors = []
    for line in proc.stdout.splitlines():
        try:
            d = json.loads(line)
        except json.JSONDecodeError:
            continue
        if "error" in d:
            errors.append(f"{Path(d['error']).name}: {d['message']}")
    missing = [j for j in jobs if not Path(j.out).exists()]
    if errors or missing or proc.returncode not in (0, 2):
        detail = "\n".join(errors) or (proc.stderr or proc.stdout).strip()[-800:]
        raise MediaError(f"فشل رسم الگرافيكس ({len(errors) or len(missing)} من {len(jobs)}): {detail}")


def _publish(bundle: Path, src: Path, name: str | None = None) -> str:
    """Copy a file into the bundle's public/ folder so a composition can staticFile() it."""
    name = name or Path(src).name
    shutil.copyfile(src, bundle / "public" / name)
    return name


def graphic_job(beat: Beat, style: Style, out: Path, public_dir: Path | None = None, index: int | None = None,
                bundle: Path | None = None, scale: float = 1.0, src: Path | None = None,
                extra_props: dict | None = None) -> RenderJob:
    """Job for an image / ai_image / entity / graphic beat. Pictures come from `src`, or for `image`
    beats from assets/img_<index>.* in `public_dir` (the episode's assets folder)."""
    bundle = bundle or ensure_bundle()
    props = {"style": _style_props(style), "durationSec": round(beat.duration, 3), **(extra_props or {})}
    if beat.kind in ("image", "ai_image"):
        if src is None and public_dir is not None:
            src = next(Path(public_dir).glob(f"img_{index}.*"), None)
        if src is None:
            raise MediaError(f"صورة الـ beat {index} مو موجودة")
        comp = "image"
        props.update(src=_publish(bundle, src), treatment=beat.treatment or style.image_treatment,
                     caption=beat.caption or "")
    elif beat.kind == "entity":
        comp = "entity"
        if src is not None:
            props["src"] = _publish(bundle, src)
    else:
        g = dict(beat.graphic or {})
        comp = g.pop("type")
        if comp == "custom":
            comp = f"custom-{g.pop('scene')}"
        props.update(g)
    return RenderJob(comp, props, Path(out), scale)


def face_fx_job(beat: Beat, style: Style, face: Path, out: Path, fps: int, channel: dict,
                bundle: Path | None = None, scale: float = 1.0, avatar: Path | None = None) -> RenderJob:
    """The presenter's own footage (`face`, already canvas-sized) wrapped in a YouTube-style scene."""
    bundle = bundle or ensure_bundle()
    ch = dict(channel)
    ch["avatar"] = _publish(bundle, avatar, "channel_avatar" + avatar.suffix) if avatar else None
    props = {"style": _style_props(style), "durationSec": round(beat.duration, 3), "fps": fps,
             "src": _publish(bundle, face), "fx": beat.fx or "none", "stickers": beat.stickers or [],
             "channel": ch}
    return RenderJob("face-fx", props, Path(out), scale)


def render_graphic(beat: Beat, style: Style, out: Path, public_dir: Path | None = None,
                   index: int | None = None, bundle: Path | None = None, scale: float = 1.0,
                   src: Path | None = None, extra_props: dict | None = None) -> Path:
    bundle = bundle or ensure_bundle()
    job = graphic_job(beat, style, out, public_dir, index, bundle, scale, src, extra_props)
    render_batch([job], bundle)
    return job.out


def render_face_fx(beat: Beat, style: Style, face: Path, out: Path, fps: int, channel: dict,
                   bundle: Path | None = None, scale: float = 1.0, avatar: Path | None = None) -> Path:
    bundle = bundle or ensure_bundle()
    job = face_fx_job(beat, style, face, out, fps, channel, bundle, scale, avatar)
    render_batch([job], bundle)
    return job.out


def render_face_frame_bg(style: Style, out_png: Path, bundle: Path | None = None, scale: float = 1.0) -> Path:
    bundle = bundle or ensure_bundle()
    job = RenderJob("face-frame-bg", {"style": _style_props(style), "durationSec": 1}, Path(out_png), scale, still=True)
    render_batch([job], bundle)
    return job.out
